# Generated by Django 2.2.19 on 2022-10-22 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20221021_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, который подписывается на автора', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Подписавшийся'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'author')},
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='Пользователь, подписанный на автора', on_delete=django.db.models.deletion.CASCADE, related_name='subscripring', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='Пост автора, на которого подписан пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='posts.Post')),
                ('user', models.ForeignKey(help_text='Пользователь, подписанный на автора', on_delete=django.db.models.deletion.CASCADE, related_name='subscribed', to=settings.AUTH_USER_MODEL, verbose_name='Подписанный')),
            ],
            options={
                'ordering': ['-user'],
            },
        ),
    ]
