# Generated by Django 2.2.19 on 2022-10-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20221022_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
